[ids]
*

[main]
capslock = overload(capslock, esc)

[capslock:C]
h = left
j = down
n = down
k = up
p = up
l = right

[control]
w = C-backspace # requires this to kitty config: map ctrl+backspace send_text all \x17
