customCommands:
  - key: "<c-c>"
    context: "files"
    prompts:
      - type: "input"
        title: "Add Commit Message with Jira prefix"
        key: "Message"

    command:
      git commit -m "$(git branch --contains | awk -v m="{{.Form.Message}}" '
      /\*/{split($2, n, /-/);
      n[1] = toupper(n[1]);
      print (n[1] "-" n[2] ":" " " m)}')"

    subprocess: true

    description: "Custom commit message"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"

gui:
  scrollHeight: 10 
