customCommands:
  - key: '<c-c>'
    command: 'git push origin {{.CheckedOutBranch.Name}} --no-verify'
    context: 'global'
    loadingText: 'Pushing with --no-verify'
    description: 'Push current branch to remote ignoring pre-push hooks'
    output: 'popup'

# customCommands:
#   - key: "<c-c>"
#     context: "files"
#     prompts:
#       - type: "input"
#         title: "Add Commit Message with Jira prefix"
#         key: "Message"
#
#     command:
#       git commit -m "$(git branch --contains | awk -v m="{{.Form.Message}}" '
#       /\*/{split($2, n, /-/);
#       n[1] = toupper(n[1]);
#       print (n[1] "-" n[2] ":" " " m)}')"
#
#     output: terminal
#
#     description: "Commit message with the jira card from branch name"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  commitPrefix:
    - pattern: "^\\w+\\/(\\w+-\\d+).*"
      replace: '$1: '
    - pattern: "^(\\w+-\\d+).*"
      replace: '$1: '

gui:
  scrollHeight: 10
  showDivergenceFromBaseBranch: onlyArrow
  commitAuthorLongLength: 2

nerdFontsVersion: '3'
